// Date: 7/23/2015 7:54:40 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.piwalker.emeraldtools.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCrystalAltar extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer Cross_1;
    ModelRenderer Cross_2;
    ModelRenderer PillarBase_A;
    ModelRenderer PillarBase_B;
    ModelRenderer PillarBase_c;
    ModelRenderer PillarBase_d;
    ModelRenderer Shape1;
  
  public ModelCrystalAltar()
  {
    textureWidth = 512;
    textureHeight = 512;
    
      Base = new ModelRenderer(this, 0, 0);
      Base.addBox(0F, 0F, 0F, 48, 16, 48);
      Base.setRotationPoint(-24F, 0F, -24F);
      Base.setTextureSize(512, 512);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      Cross_1 = new ModelRenderer(this, 0, 0);
      Cross_1.addBox(0F, 0F, 0F, 69, 1, 1);
      Cross_1.setRotationPoint(-25F, 1F, 24F);
      Cross_1.setTextureSize(512, 512);
      Cross_1.mirror = true;
      setRotation(Cross_1, 0F, 0.7853982F, 0F);
      Cross_2 = new ModelRenderer(this, 0, 0);
      Cross_2.addBox(0F, 0F, 0F, 69, 1, 1);
      Cross_2.setRotationPoint(-24F, 1F, -24F);
      Cross_2.setTextureSize(512, 512);
      Cross_2.mirror = true;
      setRotation(Cross_2, 0F, -0.7853982F, 0F);
      PillarBase_A = new ModelRenderer(this, 0, 0);
      PillarBase_A.addBox(0F, 0F, 0F, 1, 17, 1);
      PillarBase_A.setRotationPoint(-30F, -14F, 29F);
      PillarBase_A.setTextureSize(512, 512);
      PillarBase_A.mirror = true;
      setRotation(PillarBase_A, -0.3316126F, 0F, -0.3316126F);
      PillarBase_B = new ModelRenderer(this, 0, 0);
      PillarBase_B.addBox(0F, 0F, 0F, 1, 17, 1);
      PillarBase_B.setRotationPoint(29F, -13F, -30F);
      PillarBase_B.setTextureSize(512, 512);
      PillarBase_B.mirror = true;
      setRotation(PillarBase_B, 0.3316126F, 0F, 0.3316126F);
      PillarBase_c = new ModelRenderer(this, 0, 0);
      PillarBase_c.addBox(0F, 0F, 0F, 1, 17, 1);
      PillarBase_c.setRotationPoint(29F, -14F, 30F);
      PillarBase_c.setTextureSize(512, 512);
      PillarBase_c.mirror = true;
      setRotation(PillarBase_c, -0.3316126F, 0F, 0.3316126F);
      PillarBase_d = new ModelRenderer(this, 0, 0);
      PillarBase_d.addBox(0F, 0F, -3F, 1, 17, 1);
      PillarBase_d.setRotationPoint(-30F, -14F, -26F);
      PillarBase_d.setTextureSize(512, 512);
      PillarBase_d.mirror = true;
      setRotation(PillarBase_d, 0.3316126F, 0F, -0.3490659F);
      Shape1 = new ModelRenderer(this, 41, 35);
      Shape1.addBox(0F, 0F, 0F, 16, 2, 16);
      Shape1.setRotationPoint(-8F, -9F, -8F);
      Shape1.setTextureSize(512, 512);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Base.render(f5);
    Cross_1.render(f5);
    Cross_2.render(f5);
    PillarBase_A.render(f5);
    PillarBase_B.render(f5);
    PillarBase_c.render(f5);
    PillarBase_d.render(f5);
    Shape1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
  }

}
